ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER TEST_USER IDENTIFIED BY "testpassword";

GRANT CONNECT TO TEST_USER CONTAINER=CURRENT;
GRANT CREATE SESSION TO TEST_USER CONTAINER=CURRENT;
GRANT RESOURCE TO TEST_USER CONTAINER=CURRENT;
GRANT CREATE DATABASE LINK TO TEST_USER CONTAINER=CURRENT;

ALTER USER TEST_USER QUOTA 15000M ON USERS;